seg_len: 30
seg_stride: 1
for_len: 0
pose_num: 18
ckp: [4, 10, 13]
layout: 'asd'
strategy: 'NaturalConnection'
normalize_flag: 0
vid_res: [640, 480]
symm_range: False
sub_mean: False
seg_conf_th: 0.0
transform: False
divide: "random"
train_txt_path: "configs/SH_Train.txt"
test_txt_path: "configs/SH_Test.txt"
train_ratio: 0.7
vali_ratio: 0.1
test_ratio: 0.2
data_shuffle: False
train_scenes: [1, 2]
vali_scenes: [1, 2]
test_scenes: [1, 2]
