seg_len: 12
seg_stride: 1
for_len: 12
pose_num: 18
ckp: [4, 10, 13]
normalize_flag: 0
vid_res: [1920, 1080]
symm_range: True
sub_mean: False
seg_conf_th: 0.0
transform: False
divide: "random"
train_txt_path: "configs/SH_Train.txt"
test_txt_path: "configs/SH_Test.txt"
train_ratio: 0.5
vali_ratio: 0.0
test_ratio: 0.5
data_shuffle: False
train_scenes: [1, 2]
vali_scenes: [1, 2]
test_scenes: [1, 2]
