seg_len: 21
seg_stride: 1
for_len: 21
pose_num: 18
ckp: []
normalize_flag: 0
vid_res: [856, 480]
symm_range: True
sub_mean: False
seg_conf_th: 5.0
transform: False
divide: "random"
train_txt_path: "configs/SH_Train.txt"
test_txt_path: "configs/SH_Test.txt"
train_ratio: 1.0
vali_ratio: 0.0
test_ratio: 0.0
data_shuffle: False
train_scenes: []
vali_scenes: []
test_scenes: []